name: cs3midlogin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # Updated SDK version format

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Updated to a newer version

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png  # Ensure the icon path is correct

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"  # Specify the path to your app icon


